"""Bounded chain gating registry defaults.

Owns high-gate, strong-partial, structural-noise, and execution-context chain
gating definitions without scan-time registry mutation.
"""

from Virus_Scan.detection.registries.immutability import freeze_registry_value


MAJOR_ATTACK_ANCHOR_TAGS = freeze_registry_value({'amsi_scanbuffer_patch', 'archive_dropper', 'c2_beacon', 'confirmed_embedded_pe_payload', 'create_remote_thread', 'credential_dump_attempt', 'decoded_pe_payload', 'embedded_pe_payload', 'encoded_powershell', 'etw_eventwrite_patch', 'known_bad_hash', 'lsass_access', 'mimikatz_credential_dump', 'network_c2', 'powershell_exec', 'remote_command_channel', 'remote_payload_download', 'remote_thread_create', 'write_process_memory', 'yara_malware'})
BEHAVIOR_GATED_TAGS = freeze_registry_value({'script_execution', 'process_exec', 'wscript_exec', 'cscript_exec', 'vbs_execution', 'jscript_execution', 'javascript_execution', 'fileless_execution', 'lolbin_execution', 'network_download', 'remote_payload_download', 'network_c2', 'backdoor_or_c2', 'remote_command_channel', 'c2_beacon', 'c2_or_remote_command', 'archive_dropper', 'embedded_archive_payload', 'dropper_behavior', 'dll_hijack', 'dll_sideload', 'persistence', 'startup_persistence', 'run_key_mod', 'service_create', 'service_persistence', 'scheduled_task', 'schtasks_create', 'input_capture', 'keylogging_behavior', 'collection', 'user_activity_monitoring', 'spyware_behavior', 'screenshot_capture', 'screen_capture', 'exfiltration', 'network_exfiltration', 'http_upload', 'embedded_base64_payload', 'encoded_payload_candidate', 'in_memory_execution', 'macro_office', 'office_macro_execution'})
LOW_RISK_CONTEXT_REPLACEMENTS = freeze_registry_value({'script_execution': 'script_capability_context', 'process_exec': 'process_launch_capability', 'wscript_exec': 'script_host_capability', 'cscript_exec': 'script_host_capability', 'network_download': 'network_activity', 'archive_dropper': 'archive_api_context', 'embedded_archive_payload': 'archive_api_context', 'dropper_behavior': 'file_write_capability', 'dll_hijack': 'dll_load_capability', 'dll_sideload': 'dll_load_capability', 'input_capture': 'input_event_handling', 'keylogging_behavior': 'input_event_handling', 'user_activity_monitoring': 'input_event_handling', 'spyware_behavior': 'behavior_capability_context', 'screenshot_capture': 'screen_capture_capability', 'screen_capture': 'screen_capture_capability', 'collection': 'collection_capability', 'network_activity': 'network_capability', 'embedded_base64_payload': 'encoded_data_context', 'encoded_payload_candidate': 'encoded_data_context', 'macro_office': 'office_macro_context', 'office_macro_execution': 'office_macro_context', 'anti_debug': 'runtime_debug_api_capability', 'anti_vm': 'runtime_environment_probe_capability', 'anti_sandbox': 'runtime_environment_probe_capability', 'defense_evasion': 'runtime_low_level_capability', 'memory_access': 'runtime_memory_api_capability', 'memory_read': 'runtime_memory_api_capability', 'memory_write': 'runtime_memory_api_capability', 'memory_protect': 'runtime_memory_api_capability', 'memory_protection': 'runtime_memory_api_capability', 'memory_allocation': 'runtime_memory_api_capability', 'overlay_payload_after_eof': 'runtime_binary_overlay_or_padding', 'payload_decode_candidate': 'runtime_decode_capability', 'obfuscated_script': 'runtime_string_noise', 'crypto_wallet_pattern': 'runtime_crypto_string_noise', 'crypto_address_display': 'runtime_crypto_string_noise', 'il_invoke': 'runtime_interop_capability', 'IL_INVOKE': 'runtime_interop_capability', 'obfuscation_pack': 'runtime_packer_string_noise', 'packed_or_obfuscated': 'runtime_packer_string_noise', 'packer_marker': 'runtime_packer_string_noise'})
SUPPORT_ONLY_SCORE_TAGS = freeze_registry_value({'lateral_movement', 'remote_execution', 'network_activity', 'network_exfiltration', 'defense_evasion', 'scheduled_execution', 'process_injection', 'credential_access', 'packed_or_obfuscated', 'fileless_execution', 'background_transfer', 'registry_mod'})
CONCRETE_SCORE_TAGS = freeze_registry_value({'admin_share_access', 'amsi_bypass_attempt', 'amsi_scanbuffer_patch', 'assembly_load', 'at_exec', 'browser_profile_access', 'cmd_exec', 'create_remote_thread', 'credential_api_access', 'credential_dump_attempt', 'cscript_exec', 'decoded_payload_rescanned', 'defender_disable', 'dns_tunneling', 'dotnet_reflective_loader', 'dpapi_access', 'embedded_base64_payload', 'embedded_gzip_payload', 'encoded_payload', 'encoded_payload_candidate', 'encoded_powershell', 'etw_bypass_attempt', 'etw_eventwrite_patch', 'image_appended_payload', 'image_payload_confirmed', 'impacket_exec', 'installutil_exec', 'lolbin_download', 'lsass_access', 'memory_allocate', 'memory_dump', 'memory_protect', 'memory_write', 'mimikatz_credential_dump', 'msbuild_exec', 'mshta_exec', 'network_download', 'overlay_payload_after_eof', 'payload_decode_candidate', 'powershell_exec', 'process_hollowing', 'psexec_usage', 'rdp_enable_or_use', 'recovery_disable', 'reflection', 'registry_persistence', 'registry_run_key', 'regsvr32_exec', 'remote_registry', 'remote_scheduled_task', 'remote_service_creation', 'remote_thread_create', 'run_key_mod', 'rundll32_exec', 'scheduled_task', 'schtasks_create', 'security_process_kill', 'security_service_disable', 'service_create', 'shadowcopy_delete', 'smb_activity', 'startup_persistence', 'tamper_protection_disable', 'thread_execution', 'token_secret_access', 'win32_process_create', 'winrm_exec', 'wmi_exec', 'wmic_exec', 'write_process_memory', 'wscript_exec'})
SINGLE_ANCHOR_SCORE_CHAINS = freeze_registry_value({'defender_disable', 'mimikatz_credential_dump', 'shadowcopy_delete'})
CONCRETE_SCORE_TAGS = CONCRETE_SCORE_TAGS | {'admin_user_creation', 'anti_sandbox', 'anti_vm', 'archive_dropper', 'blockchain_api_access', 'blockchain_c2_polling', 'blockchain_command_parse', 'blockchain_p2p_or_rpc', 'clipboard_access', 'clipboard_crypto', 'crypto_address_display', 'crypto_wallet_clipboard_replace', 'crypto_wallet_pattern', 'dll_hijack', 'dll_sideload', 'embedded_payload_after_eof', 'http_upload', 'input_capture', 'keylogging_behavior', 'macro_office', 'miner_binary', 'mining_pool_connection', 'network_c2', 'office_macro_execution', 'packed_exe', 'pickle_callable_reference', 'pickle_dangerous_global', 'pickle_external_executable_reference', 'pickle_external_file_reference', 'pickle_external_script_reference', 'pickle_file_load_context', 'pickle_fragmented_base64_payload', 'pickle_fragmented_payload', 'pickle_reduce_opcode', 'pickle_stack_global', 'priv_esc_uac', 'privileged_group_mod', 'reflection_dotnet', 'regsvr32_sct', 'remote_command_channel', 'scriptlet_execution', 'service_persistence', 'stego_payload_suspect', 'stratum_protocol', 'uac_bypass'}
TAG_AUDIT_VERSION = 'tag_chain_audit_guardrails_v2'
TAG_WEAK_CONTEXT_ONLY = freeze_registry_value({'url_present', 'network_url', 'asset_resource_fetch', 'browser_xhr_fetch', 'game_resource_cache', 'network_activity', 'persistent_save_data', 'save_archive_access', 'renpy_save_location', 'encoded_data_context', 'base64_detected', 'base64_blob_detected', 'decoded_base64_blob', 'decoded_base64_data', 'decoded_payload_observed', 'payload_decode_candidate', 'encoded_payload_candidate', 'compressed_payload_candidate', 'compressed_payload', 'embedded_base64_payload', 'embedded_gzip_payload', 'embedded_zlib_payload', 'gzip_decode', 'zlib_decompress', 'gzip_decompress', 'possible_packed_or_encrypted_blob', 'possible_xor_encoded_blob', 'high_entropy_packed', 'very_high_entropy', 'high_entropy_sections', 'high_entropy_section', 'stego_statistical_anomaly', 'lsb_statistical_anomaly', 'stego_candidate_observation', 'stego_payload_suspect', 'image_metadata_url_reference', 'image_metadata_encoded_reference', 'embedded_archive_signature', 'embedded_zip_signature', 'embedded_7z_signature', 'embedded_rar_signature', 'magic_type_text', 'filetype_asset', 'text_file', 'actual_stage_asset', 'observed_stage_asset', 'claimed_stage_runtime', 'stage_parallel_runtime_micro_collectors', 'strict_fast_prefilter_hit', 'binary_failover_scan', 'scan_failsafe_applied', 'renpy', 'renpy_script', 'renpy_dialogue', 'renpy_label', 'screen_logic', 'image_load', 'audio_play', 'save_load', 'unity_engine', 'unity_asset', 'managed_dotnet', 'ilspy_decompile', 'rpgm', 'node_runtime', 'nwjs', 'pickle_fast_text_hint', 'pickle_fast_exec_context', 'pickle_deserialization_context', 'pickle_deep_scan_escalated', 'pickle_file_load_context', 'pickle_callable_reference', 'pickle_dangerous_global', 'pickle_reduce_opcode', 'pickle_stack_global', 'blockchain_api_access', 'blockchain_p2p_or_rpc', 'crypto_wallet_pattern', 'crypto_address_display', 'user_context', 'inline_task', 'python_bytecode_or_script'})
TAG_STRUCTURAL_ONLY = freeze_registry_value({'extension_mismatch', 'asset_extension_magic_mismatch', 'extension_magic_type_mismatch', 'filetype_misclassification', 'filetype_misclassification_low', 'filetype_misclassification_medium', 'filetype_misclassification_high', 'asset_deep_scan_escalated', 'asset_embedded_payload_signature', 'asset_embedded_script_or_url', 'embedded_command_or_url', 'embedded_pe_signature', 'possible_appended_payload', 'asset_high_entropy_tail', 'low_string_visibility', 'packer_marker', 'packed_or_obfuscated', 'engine_runtime_library', 'runtime_library', 'python_runtime_binary', 'python_runtime_library', 'renpy_runtime_library'})
TAG_BEHAVIOR_SCOREABLE = freeze_registry_value({'amsi_bypass_attempt', 'amsi_scanbuffer_patch', 'archive_dropper', 'bitsadmin_exec', 'blockchain_c2_polling', 'blockchain_command_parse', 'certutil_exec', 'clipboard_access', 'cmd_exec', 'confirmed_embedded_pe_payload', 'create_remote_thread', 'credential_api_access', 'credential_dump_attempt', 'crypto_wallet_clipboard_replace', 'cscript_exec', 'curl_exec', 'decoded_base64_binary_payload', 'decoded_base64_script', 'decoded_pe_payload', 'defender_disable', 'dns_tunneling', 'dpapi_access', 'dynamic_execution', 'embedded_archive_payload', 'embedded_payload_after_eof', 'embedded_pe_payload', 'encoded_payload', 'encoded_powershell', 'etw_bypass_attempt', 'etw_eventwrite_patch', 'file_read', 'file_rename_delete', 'file_write', 'http_upload', 'image_appended_payload', 'image_payload_confirmed', 'input_capture', 'keylogging_behavior', 'lolbin_download', 'lsass_access', 'macro_office', 'memory_allocate', 'memory_dump', 'memory_protect', 'memory_read', 'memory_write', 'mimikatz_credential_dump', 'miner_binary', 'mining_pool_connection', 'mshta_exec', 'network_c2', 'network_download', 'office_macro_execution', 'packed_exe', 'powershell_exec', 'powershell_invoke_expression', 'process_hollowing', 'ransom_note_indicator', 'recovery_disable', 'registry_persistence', 'registry_run_key', 'regsvr32_exec', 'regsvr32_sct', 'remote_command_channel', 'remote_payload_download', 'remote_service_creation', 'remote_thread_create', 'run_key_mod', 'rundll32_exec', 'scheduled_task', 'schtasks_create', 'scriptlet_execution', 'security_process_kill', 'security_service_disable', 'service_create', 'shadowcopy_delete', 'startup_persistence', 'stratum_protocol', 'thread_execution', 'token_secret_access', 'wget_exec', 'write_process_memory', 'wscript_exec'})
TAG_CHAIN_LINK_REQUIRED = TAG_WEAK_CONTEXT_ONLY | TAG_STRUCTURAL_ONLY
SUPPORT_ONLY_SCORE_TAGS = SUPPORT_ONLY_SCORE_TAGS | TAG_WEAK_CONTEXT_ONLY | TAG_STRUCTURAL_ONLY
TAG_RISK_SCORE_ZERO_TAGS = TAG_WEAK_CONTEXT_ONLY | TAG_STRUCTURAL_ONLY
TAG_RISK_SCORE_OVERRIDES = freeze_registry_value({'archive_dropper': 8.0, 'decoded_base64_binary_payload': 4.0, 'decoded_base64_script': 2.0, 'embedded_archive_payload': 2.0, 'encoded_payload': 4.0, 'encoded_payload_candidate': 0.0})
STRUCTURAL_PE_NOISE_TAGS = freeze_registry_value({'pe_x64', 'pe_x86', 'pe_section_.text', 'pe_section_.data', 'pe_section_.rdata', 'pe_section_.pdata', 'pe_section_.rsrc', 'pe_section_.tls', 'pe_section_.buildid', 'dll_load', 'high_entropy_section', 'high_entropy_sections', 'high_entropy_packed', 'very_high_entropy', 'encoded_payload_candidate', 'possible_packed_or_encrypted_blob', 'possible_xor_encoded_blob', 'packed_or_obfuscated', 'magic_binary_blob', 'magic_type_unknown_binary_blob', 'observed_stage_binary', 'actual_stage_binary', 'router_stage_binary', 'memory_access', 'memory_read', 'memory_protect', 'memory_protection', 'low_string_visibility'})
HIGH_CONFIDENCE_ATTACK_ANCHOR_TAGS = freeze_registry_value({'amsi_scanbuffer_patch', 'cmd_exec', 'create_remote_thread', 'credential_dump_attempt', 'defender_disable', 'dns_tunneling', 'encoded_powershell', 'etw_eventwrite_patch', 'lsass_access', 'mimikatz_credential_dump', 'powershell_exec', 'process_hollowing', 'registry_run_key', 'remote_scheduled_task', 'remote_service_creation', 'remote_thread_create', 'run_key_mod', 'scheduled_task', 'schtasks_create', 'service_create', 'shadowcopy_delete', 'vssadmin_delete', 'wbadmin_delete', 'win32_process_create', 'wmi_exec', 'wmic_exec', 'write_process_memory'})
WEAK_MEMORY_ONLY_TAGS = freeze_registry_value({'memory_access', 'memory_read', 'memory_protect', 'memory_protection', 'memory_allocate', 'memory_write', 'thread_execution', 'process_injection'})
HIGH_GATE_VERSION = 'anchor_chain_high_gate_v2_high_unlocking_chains'
HIGH_GATE_MAX_WITHOUT_AUTHORITY = 39.0
RENPY_FAILSAFE_ONLY_MAX_SCORE = 12.0
HIGH_GATE_SINGLE_ANCHOR_TAGS = freeze_registry_value({'amsi_scanbuffer_patch', 'cmd_exec', 'create_remote_thread', 'credential_dump_attempt', 'cscript_exec', 'defender_disable', 'dns_tunneling', 'encoded_powershell', 'etw_eventwrite_patch', 'installutil_exec', 'lsass_access', 'mimikatz_credential_dump', 'msbuild_exec', 'mshta_exec', 'powershell_exec', 'process_hollowing', 'registry_run_key', 'regsvr32_exec', 'remote_scheduled_task', 'remote_service_creation', 'remote_thread_create', 'run_key_mod', 'rundll32_exec', 'schtasks_create', 'security_process_kill', 'security_service_disable', 'service_create', 'shadowcopy_delete', 'startup_persistence', 'vssadmin_delete', 'wbadmin_delete', 'win32_process_create', 'wmi_exec', 'wmic_exec', 'write_process_memory', 'wscript_exec'})
CONCRETE_SCORE_TAGS = (CONCRETE_SCORE_TAGS | TAG_BEHAVIOR_SCOREABLE) - (TAG_WEAK_CONTEXT_ONLY | TAG_STRUCTURAL_ONLY)
HIGH_GATE_WEAK_OR_STRUCTURAL_TAGS = freeze_registry_value({'high_entropy_section', 'high_entropy_sections', 'high_entropy_packed', 'very_high_entropy', 'encoded_payload_candidate', 'possible_packed_or_encrypted_blob', 'possible_xor_encoded_blob', 'packed_or_obfuscated', 'magic_binary_blob', 'magic_type_unknown_binary_blob', 'binary_failover_scan', 'scan_failsafe_applied', 'low_string_visibility', 'dll_load', 'pe_x64', 'pe_x86', 'pe_section_.text', 'pe_section_.data', 'pe_section_.rdata', 'pe_section_.pdata', 'pe_section_.rsrc', 'pe_section_.tls', 'pe_section_.buildid', 'memory_access', 'memory_read', 'memory_protect', 'memory_protection', 'memory_allocate', 'memory_write', 'thread_execution', 'process_injection', 'router_stage_binary', 'observed_stage_binary', 'actual_stage_binary', 'claimed_stage_runtime'})
RENPY_CONTEXT_TAGS = freeze_registry_value({'renpy', 'renpy_bytecode', 'renpy_script'})
RENPY_FAILSAFE_ONLY_TAGS = freeze_registry_value({'binary_failover_scan', 'scan_failsafe_applied', 'magic_binary_blob', 'magic_type_unknown_binary_blob', 'unknown_binary_blob', 'high_entropy_section', 'high_entropy_sections', 'possible_packed_or_encrypted_blob', 'possible_xor_encoded_blob', 'encoded_payload_candidate', 'packed_or_obfuscated', 'low_string_visibility'})
