"""Detection registry startup publication.

The detection registry is now owned by a single immutable
DetectionRegistrySnapshot.  Startup publishes the explicit snapshot values for
startup readers without allowing detection stages to hydrate or mutate registry
defaults from shared runtime state.
"""
from __future__ import annotations

from Virus_Scan.detection.registries.publication import publish_init_values
from Virus_Scan.detection.registries.snapshot import (
    DEFAULT_DETECTION_REGISTRY_SNAPSHOT,
    DetectionRegistrySnapshot,
    DETECTION_CONSTANT_DEFAULTS,
)

CONTEXTUAL_BASELINE_VERSION = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("CONTEXTUAL_BASELINE_VERSION")
CONTEXTUAL_BASELINE_MIN_FILES = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("CONTEXTUAL_BASELINE_MIN_FILES")
CONTEXTUAL_BASELINE_COMMON_TAG_PROB = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("CONTEXTUAL_BASELINE_COMMON_TAG_PROB")
CONTEXTUAL_BASELINE_STRONG_COMMON_TAG_PROB = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("CONTEXTUAL_BASELINE_STRONG_COMMON_TAG_PROB")
CONTEXTUAL_BASELINE_MAX_REDUCTION = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("CONTEXTUAL_BASELINE_MAX_REDUCTION")
CONTEXTUAL_BASELINE_MIN_KEEP_WITHOUT_ANCHOR = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("CONTEXTUAL_BASELINE_MIN_KEEP_WITHOUT_ANCHOR")
CONTEXTUAL_BASELINE_MIN_KEEP_WITH_ANCHOR = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("CONTEXTUAL_BASELINE_MIN_KEEP_WITH_ANCHOR")
CONTEXTUAL_BASELINE_NEVER_LEARN_DANGEROUS = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("CONTEXTUAL_BASELINE_NEVER_LEARN_DANGEROUS")
TRIAGE_LEARNING_BLOCK_TAGS = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("TRIAGE_LEARNING_BLOCK_TAGS")
CONTEXTUAL_DANGEROUS_ANCHOR_TAGS = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("CONTEXTUAL_DANGEROUS_ANCHOR_TAGS")
CONTEXTUAL_WEAK_NOISE_BUCKETS = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("CONTEXTUAL_WEAK_NOISE_BUCKETS")
BEHAVIOR_MODEL_VERSION = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("BEHAVIOR_MODEL_VERSION")
VECTOR_FEATURE_NAMES = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("VECTOR_FEATURE_NAMES")
NON_EXECUTION_CAPABILITIES = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("NON_EXECUTION_CAPABILITIES")
CONTAINER_EXECUTION_CAPABILITIES = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("CONTAINER_EXECUTION_CAPABILITIES")
QUALITY_GATE_VERSION = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("QUALITY_GATE_VERSION")
ENGINE_BASELINE_CONFIDENCE_THRESHOLD = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("ENGINE_BASELINE_CONFIDENCE_THRESHOLD")
BASELINE_MATURITY_COLD_FILES = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("BASELINE_MATURITY_COLD_FILES")
BASELINE_MATURITY_WARM_FILES = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("BASELINE_MATURITY_WARM_FILES")
CONFIRMED_API_HINTS = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("CONFIRMED_API_HINTS")
STRUCTURAL_NOISE_TAGS = DEFAULT_DETECTION_REGISTRY_SNAPSHOT.value("STRUCTURAL_NOISE_TAGS")


def detection_registry_snapshot() -> DetectionRegistrySnapshot:
    return DEFAULT_DETECTION_REGISTRY_SNAPSHOT


def init_detection_constants() -> object:
    registry_snapshot = DEFAULT_DETECTION_REGISTRY_SNAPSHOT
    return publish_init_values((
        ("DETECTION_REGISTRY_SNAPSHOT", registry_snapshot),
        *registry_snapshot.publication_items(),
    ))


__all__ = (
    "BASELINE_MATURITY_COLD_FILES",
    "BASELINE_MATURITY_WARM_FILES",
    "BEHAVIOR_MODEL_VERSION",
    "CONFIRMED_API_HINTS",
    "CONTAINER_EXECUTION_CAPABILITIES",
    "CONTEXTUAL_BASELINE_COMMON_TAG_PROB",
    "CONTEXTUAL_BASELINE_MAX_REDUCTION",
    "CONTEXTUAL_BASELINE_MIN_FILES",
    "CONTEXTUAL_BASELINE_MIN_KEEP_WITHOUT_ANCHOR",
    "CONTEXTUAL_BASELINE_MIN_KEEP_WITH_ANCHOR",
    "CONTEXTUAL_BASELINE_NEVER_LEARN_DANGEROUS",
    "CONTEXTUAL_BASELINE_STRONG_COMMON_TAG_PROB",
    "CONTEXTUAL_BASELINE_VERSION",
    "CONTEXTUAL_DANGEROUS_ANCHOR_TAGS",
    "CONTEXTUAL_WEAK_NOISE_BUCKETS",
    "DETECTION_CONSTANT_DEFAULTS",
    "ENGINE_BASELINE_CONFIDENCE_THRESHOLD",
    "NON_EXECUTION_CAPABILITIES",
    "QUALITY_GATE_VERSION",
    "STRUCTURAL_NOISE_TAGS",
    "TRIAGE_LEARNING_BLOCK_TAGS",
    "VECTOR_FEATURE_NAMES",
    "DetectionRegistrySnapshot",
    "detection_registry_snapshot",
    "init_detection_constants",
)
