"""Bounded runtime/profile registry defaults.

Owns Ren'Py updater, runtime-library, and contextual profile suppression policy
definitions used by detection profile classification.
"""

from Virus_Scan.detection.registries.immutability import freeze_registry_value

BROAD_UNVALIDATED_TAGS = freeze_registry_value({'lateral_movement', 'remote_execution', 'credential_access', 'network_exfiltration', 'process_injection', 'defense_evasion', 'script_execution', 'scheduled_task'})
RPYC_NOISE_TAGS = freeze_registry_value({'magic_binary_blob', 'magic_type_unknown_binary_blob', 'unknown_binary_blob', 'possible_packed_or_encrypted_blob', 'possible_xor_encoded_blob', 'encoded_payload_candidate', 'high_entropy_sections', 'high_entropy_packed', 'very_high_entropy', 'low_string_visibility', 'packed_or_obfuscated', 'actual_stage_binary', 'claimed_stage_runtime', 'observed_stage_binary', 'extension_mismatch', 'binary_failover_scan', 'scan_failsafe_applied'})
RPYC_HIGH_RISK_TAGS = freeze_registry_value({'wmi_exec', 'win32_process_create', 'remote_execution', 'lateral_movement', 'admin_share_access', 'smb_activity', 'impacket_exec', 'remote_service_creation', 'remote_scheduled_task', 'remote_registry', 'credential_access', 'credential_dump_attempt', 'token_secret_access', 'credential_api_access', 'lsass_access', 'memory_dump', 'network_exfiltration', 'network_activity', 'dns_tunneling', 'token_exfiltration', 'powershell_exec', 'cmd_exec', 'process_exec', 'fileless_execution', 'process_injection', 'memory_write', 'thread_execution', 'memory_protect'})
PICKLE_GRAPH_PROOF_TAGS = freeze_registry_value({'pickle_opcode_graph_analyzed', 'pickle_dangerous_global'})
PICKLE_GRAPH_PROTECTED_TAGS = freeze_registry_value({'pickle_dangerous_global', 'pickle_callable_reference', 'script_execution', 'process_exec', 'code_execution'})
ASSET_RESOURCE_FETCH_TERMS = freeze_registry_value(['xmlhttprequest', 'fetch(', 'image.src', 'audio.src', 'video.src', "xhr.open('get'", 'xhr.open("get"', '.src =', 'fs.writefile'])
ASSET_RESOURCE_PATH_TERMS = freeze_registry_value(['game/', 'assets/', 'asset/', 'images/', 'image/', 'audio/', 'voice/', 'music/', 'fonts/', 'font/', 'renpy/', 'www/', 'gui/'])
RESOURCE_CACHE_TERMS = freeze_registry_value(['flush_cache_file', 'to_unlink', 'downloadneeded', 'process_downloaded_resources', 'renpy.config.gamedir', 'browser cache', 'placeholder', 'uploaded to gpu'])
REMOTE_PAYLOAD_DOWNLOAD_TERMS = freeze_registry_value(['powershell', 'invoke-webrequest', 'iwr ', 'curl', 'wget', 'certutil', 'bitsadmin', 'downloadfile', 'downloadstring', 'urldownloadtofile', 'start-process', 'subprocess', 'os.system', 'createprocess', 'shellexecute'])
REMOTE_PAYLOAD_FILE_TERMS = freeze_registry_value(['.exe', '.dll', '.ps1', '.bat', '.cmd', '.hta', '.vbs', '.jse', '.scr', '.msi', '.jar', 'application/octet-stream'])
C2_TASKING_TERMS = freeze_registry_value(['beacon', 'tasking', 'command', 'cmd=', 'shell', 'getcommand', 'post /api', '/api/checkin', 'checkin', 'check-in', 'poll', 'heartbeat', 'sleep jitter', '/gate.php', '/panel/', 'reverse shell', 'implant'])
COMMAND_EXECUTION_TERMS = freeze_registry_value(['eval(', 'exec(', 'subprocess', 'os.system', 'popen(', 'powershell', 'cmd.exe', 'createprocess', 'shellexecute', 'winexec'])
_KNOWN_PYTHON_RUNTIME_LIBRARY_NAMES = freeze_registry_value({'bootstrap.py', 'python.py', 'core.py', 'display.py', 'event.py', 'focus.py', 'render.py'})
_KNOWN_PYTHON_RUNTIME_LIBRARY_PATH_HINTS = freeze_registry_value({'renpy', 'renpy_base', 'renpy.app', 'renpy-', 'renpy_runtime', 'renpy_runtime_library'})
_RENPY_UPDATER_FILENAMES = freeze_registry_value({'00updater.rpy', '00updater.rpyc'})
_RENPY_UPDATER_SUPPRESS_TAGS = freeze_registry_value({'archive_dropper', 'dropper_behavior', 'network_download_execute', 'embedded_archive_payload', 'obfuscation_pack', 'packed_or_obfuscated', 'packer_marker', 'stage_hit:archive dropper', 'stage_hit:explicit packer marker', 'staged_detection', 'remote_payload_download'})
_RENPY_UPDATER_REPLACEMENTS = freeze_registry_value({'network_download': 'renpy_update_download_capability', 'network_activity': 'renpy_update_download_capability', 'process_exec': 'renpy_zsync_process_capability', 'python_process_exec': 'renpy_zsync_process_capability', 'bytecode_subprocess': 'renpy_zsync_process_capability', 'save_archive_access': 'renpy_update_archive_apply_capability', 'persistent_save_data': 'persistent_update_state', 'dynamic_execution': 'renpy_updater_runtime_execution_capability'})
_RENPY_UPDATER_HARD_ANCHOR_TAGS = freeze_registry_value({'yara_malware', 'known_bad_hash', 'malware_family', 'powershell_encoded', 'encoded_powershell', 'cmd_shell_exec', 'cmd_exec', 'powershell_exec', 'credential_access', 'credential_dump_attempt', 'token_theft', 'token_secret_access', 'discord_webhook', 'telegram_bot_api', 'pastebin_raw_download', 'suspicious_ip_url', 'autorun_persistence', 'registry_run_key', 'scheduled_task_create', 'schtasks_create', 'process_injection', 'embedded_pe_payload', 'decoded_pe_payload', 'confirmed_embedded_pe_payload', 'payload_decode_confirmed', 'c2_beacon', 'network_c2', 'backdoor_or_c2', 'remote_command_channel', 'network_exfiltration', 'http_upload', 'token_exfiltration', 'renpy_updater_external_process_abuse', 'renpy_updater_download_exec_abuse', 'renpy_updater_persistence_abuse', 'renpy_updater_suspicious_endpoint', 'renpy_updater_payload_staging_abuse'})
_RENPY_UPDATER_HARD_ANCHOR_TEXT = freeze_registry_value(['powershell -enc', 'encodedcommand', 'invoke-expression', 'iex(', 'cmd.exe /c', 'wscript.shell', 'mshta.exe', 'regsvr32.exe', 'rundll32.exe', 'schtasks /create', 'currentversion\\run', 'discord.com/api/webhooks', 'api.telegram.org', 'pastebin.com/raw', 'mimikatz', 'sekurlsa', 'minidumpwritedump', 'lsass.exe', 'writeprocessmemory', 'createremotethread', 'virtualallocex'])
_RUNTIME_LIBRARY_NAME_HINTS = freeze_registry_value({'librenpython.so', 'librenpython.dylib', 'renpython.dll', 'python.dll', 'pythonw.dll', 'python.exe', 'pythonw.exe', 'libpython3.9.dll', 'libpython3.10.dll', 'libpython3.11.dll', 'libpython3.12.dll', 'libpython3.13.dll', 'libwinpthread-1.dll', 'libgcc_s_seh-1.dll', 'libgcc_s_dw2-1.dll', 'libstdc++-6.dll', 'libssp-0.dll', 'libgomp-1.dll', 'unityplayer.dll', 'gameassembly.dll', 'mono.dll', 'mono-2.0-bdwgc.dll', 'libmonobdwgc-2.0.so', 'libmono.so', 'libunity.so', 'libil2cpp.so', 'nw.dll', 'node.dll', 'node.exe', 'libnode.so', 'ffmpeg.dll', 'libffmpeg.so', 'chrome_elf.dll', 'libcef.dll', 'cefsharp.core.dll', 'cefsharp.dll', 'sdl2.dll', 'sdl2_image.dll', 'openal32.dll', 'libopenal.so', 'avcodec.dll', 'avformat.dll', 'avutil.dll', 'd3dcompiler_47.dll', 'libvulkan.so', 'vulkan-1.dll'})
_RUNTIME_LIBRARY_PREFIX_HINTS = ('libpython', 'python3', 'librenpython', 'libwinpthread', 'libgcc', 'libstdc++', 'libssp', 'libgomp', 'libmono', 'libunity', 'libil2cpp', 'unityplayer', 'gameassembly', 'mono-', 'node', 'nw', 'chrome_elf', 'libcef', 'cefsharp', 'd3dcompiler', 'sdl2', 'openal', 'avcodec', 'avformat', 'avutil', 'libav', 'libvpx', 'libwebp', 'libpng', 'libjpeg')
_RUNTIME_LIBRARY_PATH_HINTS = freeze_registry_value({'lib', 'libs', 'lib64', 'renpy', 'renpy.app', 'py3-linux-x86_64', 'py2-linux', 'py3-windows', 'py2-windows', 'mono', 'monobleedingedge', 'managed', 'plugins', 'nwjs', 'electron', 'cef', 'runtime', 'jre', 'bin'})
_RUNTIME_LIBRARY_EXTS = freeze_registry_value({'.dll', '.so', '.dylib', '.pyd', '.node', '.exe'})
_RUNTIME_CAPABILITY_NOISE_TAGS = freeze_registry_value({'archive_dropper', 'dropper_behavior', 'embedded_archive_payload', 'base64', 'payload_decode_candidate', 'embedded_base64_payload', 'encoded_payload_candidate', 'dll_hijack', 'dll_sideload', 'dll_load', 'dll_load_capability', 'assembly_load', 'reflection', 'il_reflection', 'network_download', 'network_activity', 'http_upload', 'backdoor_or_c2', 'network_c2', 'remote_command_channel', 'c2_or_remote_command', 'c2_beacon', 'exfiltration', 'network_exfiltration', 'collection', 'input_capture', 'keylogging_behavior', 'clipboard_access', 'macro_office', 'office_macro_execution', 'script_execution', 'memory_allocate', 'memory_allocation', 'memory_access', 'memory_read', 'memory_write', 'memory_protect', 'memory_protection', 'thread_execution', 'process_injection', 'in_memory_execution', 'shellcode_exec', 'anti_debug', 'anti_vm', 'anti_sandbox', 'defense_evasion', 'remote_execution', 'lateral_movement', 'overlay_payload_after_eof', 'obfuscated_script', 'crypto_wallet_pattern', 'crypto_address_display', 'il_invoke', 'IL_INVOKE', 'obfuscation_pack', 'packed_or_obfuscated', 'packer_marker'})
_RUNTIME_STRONG_ATTACK_CONTEXT = freeze_registry_value(['powershell -enc', 'encodedcommand', 'invoke-expression', 'iex(', 'cmd.exe /c', 'wscript.shell', 'mshta.exe', 'rundll32.exe', 'regsvr32.exe', 'schtasks /create', 'wmic process call create', 'createprocessw(', 'createprocessa(', 'writeprocessmemory', 'createremotethread', 'ntcreatethreadex', 'queueuserapc', 'mimikatz', 'sekurlsa', 'minidumpwritedump', 'lsass.exe', 'amsiscanbuffer', 'discord.com/api/webhooks', 'api.telegram.org', '/gate.php', '/panel/', 'reverse shell'])
_LIBRARY_BASELINE_VERSION = 'library_behavior_baseline_v1'
_LIBRARY_BASELINE_NORMAL_TAGS = freeze_registry_value({'renpy_python_runtime_source': {'script_execution', 'process_exec', 'bytecode_exec', 'bytecode_eval', 'bytecode_subprocess', 'code_execution', 'pickle_deserialization_context', 'marshal_load', 'marshal_loads', 'payload_decode_candidate', 'obfuscated_script', 'obfuscation_pack', 'packed_or_obfuscated', 'packer_marker', 'persistent_save_data', 'save_archive_access', 'archive_dropper', 'embedded_archive_payload', 'dropper_behavior', 'network_activity', 'network_download', 'network_download_execute', 'process_launch_capability', 'runtime_code_execution_capability', 'runtime_eval_capability', 'runtime_exec_capability', 'runtime_process_capability', 'runtime_serialization_capability', 'runtime_import_capability', 'stage_hit:archive dropper', 'stage_hit:explicit packer marker', 'staged_detection', 'renpy_official_updater', 'renpy_update_download_capability', 'renpy_update_archive_apply_capability', 'renpy_zsync_process_capability', 'persistent_update_state', 'renpy_updater_baseline_v1', 'renpy_updater_dropper_chain_suppressed'}, 'runtime_engine_binary': {'script_execution', 'process_exec', 'archive_dropper', 'embedded_archive_payload', 'dropper_behavior', 'network_activity', 'network_download', 'network_download_execute', 'dll_load', 'dll_load_capability', 'assembly_load', 'reflection', 'il_reflection', 'base64', 'payload_decode_candidate', 'encoded_payload_candidate', 'embedded_base64_payload', 'persistence', 'persistent_save_data', 'save_archive_access', 'packer_marker', 'packed_or_obfuscated', 'obfuscation_pack', 'stage_hit:archive dropper', 'stage_hit:explicit packer marker', 'staged_detection'}})
_LIBRARY_BASELINE_REPLACEMENTS = freeze_registry_value({'script_execution': 'runtime_code_execution_capability', 'code_execution': 'runtime_code_execution_capability', 'bytecode_exec': 'runtime_code_execution_capability', 'bytecode_eval': 'runtime_eval_capability', 'bytecode_subprocess': 'runtime_process_capability', 'process_exec': 'runtime_process_capability', 'network_download': 'runtime_network_capability', 'network_download_execute': 'runtime_network_capability', 'archive_dropper': 'runtime_archive_capability', 'embedded_archive_payload': 'runtime_archive_capability', 'dropper_behavior': 'runtime_archive_capability', 'packer_marker': 'runtime_compression_or_pack_context', 'obfuscation_pack': 'runtime_compression_or_pack_context', 'packed_or_obfuscated': 'runtime_compression_or_pack_context', 'marshal_load': 'runtime_serialization_capability', 'marshal_loads': 'runtime_serialization_capability', 'persistence': 'runtime_state_capability', 'persistent_save_data': 'runtime_state_capability', 'save_archive_access': 'runtime_state_capability', 'stage_hit:archive dropper': 'runtime_stage_hit_suppressed', 'stage_hit:explicit packer marker': 'runtime_stage_hit_suppressed'})
_LIBRARY_BASELINE_HARD_PROOF_TAGS = freeze_registry_value({'yara_malware', 'known_bad_hash', 'malware_family', 'confirmed_embedded_pe_payload', 'decoded_pe_payload', 'embedded_pe_payload', 'image_payload_confirmed', 'confirmed_stego_payload', 'mimikatz_credential_dump', 'lsass_access', 'credential_dump_attempt', 'amsi_scanbuffer_patch', 'etw_eventwrite_patch', 'process_injection', 'write_process_memory', 'create_remote_thread', 'remote_thread_create', 'encoded_powershell', 'powershell_exec', 'c2_beacon', 'backdoor_or_c2', 'network_c2', 'c2_or_remote_command'})
