"""Tag byte-pattern defaults owned by tag behavior detection."""
from __future__ import annotations

from Virus_Scan.detection.registries.immutability import freeze_registry_value

TAG_PATTERNS = freeze_registry_value({'admin_share_access': (b'admin$', b'ipc$', b'c$', b'\\admin$', b'\\ipc$'),
 'admin_user_creation': (b'net user', b'net.exe user', b'new-localuser'),
 'amsi_bypass_attempt': (b'amsi', b'amsiscanbuffer', b'amsi.dll', b'amsiinitfailed'),
 'at_exec': (b'at.exe',),
 'bitsadmin_exec': (b'bitsadmin',),
 'blockchain_api_access': (b'etherscan.io',
                           b'api.etherscan.io',
                           b'blockstream.info',
                           b'blockchain.info',
                           b'blockchair.com',
                           b'mempool.space',
                           b'publicnode.com',
                           b'infura.io',
                           b'alchemy.com',
                           b'ankr.com',
                           b'eth_gettransaction',
                           b'eth_getlogs',
                           b'eth_call',
                           b'eth_blocknumber',
                           b'eth_getblockby',
                           b'bitcoin-cli',
                           b'getrawtransaction'),
 'blockchain_p2p_or_rpc': (b'ethereum-sepolia',
                           b'ethereum-mainnet',
                           b'jsonrpc',
                           b'eth_sendrawtransaction',
                           b'eth_getbalance',
                           b'web3',
                           b'ethers.js',
                           b'bitcoin rpc',
                           b'monero daemon',
                           b'daemon address'),
 'browser_credential_access': (b'login data', b'cookies.sqlite'),
 'browser_profile_access': (b'login data',
                            b'local state',
                            b'cookies',
                            b'cookies.sqlite',
                            b'web data',
                            b'places.sqlite'),
 'certutil_exec': (b'certutil',),
 'clipboard_access': (b'clipboard',),
 'cloud_upload': (b's3.amazonaws', b'azureblob'),
 'cmd_exec': (b'cmd.exe',),
 'credential_api_access': (b'credread',
                           b'credenumerate',
                           b'lsagetlogonsessiondata',
                           b'lsaenumeratelogonsessions',
                           b'minidumpwritedump'),
 'credential_dump_attempt': (b'sekurlsa', b'dumpcred', b'mimikatz'),
 'cron_modify': (b'crontab',),
 'crypto_wallet_pattern': (b'bc1', b'xmr', b'ethereum', b'bitcoin', b'monero', b'wallet address'),
 'curl_exec': (b'curl',),
 'defender_disable': (b'set-mppreference',
                      b'disableantispyware',
                      b'disablerealtimemonitoring',
                      b'add-mppreference',
                      b'exclusionpath'),
 'dns_tunneling': (b'dns', b'query'),
 'dpapi_access': (b'cryptunprotectdata', b'dpapi', b'masterkey', b'protect\\', b'microsoft\\protect'),
 'encoded_powershell': (b'-enc', b'encodedcommand'),
 'etw_bypass_attempt': (b'etweventwrite',
                        b'etwpatch',
                        b'etw patch',
                        b'nttraceevent',
                        b'patch etw',
                        b'disable etw',
                        b'etweventwrite'),
 'file_collection': (b'findfirstfile', b'findnextfile'),
 'firewall_rule_change': (b'netsh advfirewall', b'new-netfirewallrule', b'set-netfirewallprofile'),
 'ftp_transfer': (b'ftp',),
 'http_upload': (b'uploadstring',
                 b'uploadfile',
                 b'postasync',
                 b'http post',
                 b'multipart/form-data',
                 b'content-disposition: form-data'),
 'impacket_exec': (b'impacket', b'smbexec', b'wmiexec', b'atexec', b'psexec.py'),
 'keylogging_behavior': (b'getasynckeystate', b'keybd_event'),
 'local_admin_add': (b'net localgroup administrators',
                     b'localgroup administrators',
                     b'administrators /add',
                     b'add-localgroupmember',
                     b'groupadd sudo',
                     b'usermod -ag sudo'),
 'log_clearing': (b'clear-eventlog', b'eventlog.clear', b'wevtutil cl', b'wevtutil.exe cl', b'remove-eventlog'),
 'lsass_access': (b'lsass',),
 'memory_dump': (b'minidump', b'dump'),
 'memory_read': (b'readprocessmemory',),
 'memory_write': (b'writeprocessmemory',),
 'miner_binary': (b'xmrig', b'xmr-stak', b'cpuminer', b'nanominer', b't-rex miner', b'teamredminer'),
 'mshta_exec': (b'mshta',),
 'obfuscated_script': (b'obfus', b'fromcharcode', b'string.fromcharcode', b'charcode', b'xor', b'base64'),
 'powershell_exec': (b'powershell', b'pwsh'),
 'process_exec': (b'createprocess', b'winexec'),
 'psexec_usage': (b'psexec', b'psexec64', b'paexec', b'remcom'),
 'recovery_disable': (b'bcdedit',
                      b'recoveryenabled no',
                      b'bootstatuspolicy ignoreallfailures',
                      b'wbadmin delete catalog'),
 'regsvr32_exec': (b'regsvr32',),
 'remote_registry': (b'reg connect', b'remote registry', b'reg.exe add \\'),
 'remote_scheduled_task': (b'schtasks /s', b'schtasks.exe /s', b'/tn', b'/tr'),
 'remote_service_creation': (b'createservice',
                             b'createservicea',
                             b'createservicew',
                             b'sc create',
                             b'sc.exe create',
                             b'svcctl',
                             b'openscmanager',
                             b'openscmanagera',
                             b'openscmanagerw',
                             b'startservice',
                             b'changeserviceconfig'),
 'run_key_mod': (b'\\run\\',),
 'runas_usage': (b'runas',),
 'rundll32_exec': (b'rundll32',),
 'sam_access': (b'sam\\', b'security\\sam'),
 'schtasks_create': (b'schtasks',),
 'screenshot_capture': (b'bitblt', b'printwindow'),
 'security_process_kill': (b'taskkill',
                           b'/im msmpeng',
                           b'/im windefend',
                           b'/im avp',
                           b'/im avg',
                           b'/im sophos',
                           b'/im sentinel'),
 'security_service_disable': (b'sc stop windefend',
                              b'sc config windefend',
                              b'net stop windefend',
                              b'stop-service windefend'),
 'service_create': (b'createservice',
                    b'createservicea',
                    b'createservicew',
                    b'new-service',
                    b'sc create',
                    b'sc.exe create'),
 'service_persistence': (b'startservice',
                         b'changeserviceconfig',
                         b'service_auto_start',
                         b'localsystem',
                         b'service_all_access'),
 'shadowcopy_delete': (b'vssadmin delete shadows',
                       b'wmic shadowcopy delete',
                       b'delete shadows',
                       b'resize shadowstorage'),
 'smb_activity': (b'smbexec', b'wmiexec', b'psexec.py', b'impacket', b'smb2', b'tree_connect'),
 'stratum_protocol': (b'stratum+tcp://', b'stratum+ssl://', b'mining.subscribe', b'mining.authorize'),
 'systemd_modify': (b'systemctl',),
 'tamper_protection_disable': (b'tamperprotection', b'disabletamperprotection'),
 'token_impersonation': (b'impersonatetoken', b'duplicatetoken'),
 'token_secret_access': (b'oauth',
                         b'refresh_token',
                         b'access_token',
                         b'aws_access_key_id',
                         b'secret_access_key',
                         b'azure',
                         b'gcp',
                         b'jwt'),
 'uac_bypass': (b'uac', b'bypass'),
 'url_present': (b'http://', b'https://'),
 'vault_access': (b'vault',),
 'wget_exec': (b'wget',),
 'winrm_exec': (b'winrm', b'new-pssession', b'enter-pssession', b'invoke-command', b'pssession'),
 'wmi_exec': (b'wmic',
              b'win32_process',
              b'win32_process.create',
              b'invoke-wmimethod',
              b'invoke-cimmethod',
              b'get-wmiobject'),
 'wscript_exec': (b'wscript', b'cscript')})

__all__ = ("TAG_PATTERNS",)
